pub struct DefaultFeedWebSource {
    pub title: &'static str,
    pub domain: &'static str,
    pub html_url: &'static str,
    pub xml_url: &'static str,
}

pub const DEFAULT_FEED_WEB_SOURCES: &[DefaultFeedWebSource] = &[
    DefaultFeedWebSource {
        title: "simonwillison.net",
        domain: "simonwillison.net",
        html_url: "https://simonwillison.net",
        xml_url: "https://simonwillison.net/atom/everything/",
    },
    DefaultFeedWebSource {
        title: "jeffgeerling.com",
        domain: "jeffgeerling.com",
        html_url: "https://jeffgeerling.com",
        xml_url: "https://www.jeffgeerling.com/blog.xml",
    },
    DefaultFeedWebSource {
        title: "seangoedecke.com",
        domain: "seangoedecke.com",
        html_url: "https://seangoedecke.com",
        xml_url: "https://www.seangoedecke.com/rss.xml",
    },
    DefaultFeedWebSource {
        title: "krebsonsecurity.com",
        domain: "krebsonsecurity.com",
        html_url: "https://krebsonsecurity.com",
        xml_url: "https://krebsonsecurity.com/feed/",
    },
    DefaultFeedWebSource {
        title: "daringfireball.net",
        domain: "daringfireball.net",
        html_url: "https://daringfireball.net",
        xml_url: "https://daringfireball.net/feeds/main",
    },
    DefaultFeedWebSource {
        title: "ericmigi.com",
        domain: "ericmigi.com",
        html_url: "https://ericmigi.com",
        xml_url: "https://ericmigi.com/rss.xml",
    },
    DefaultFeedWebSource {
        title: "antirez.com",
        domain: "antirez.com",
        html_url: "http://antirez.com",
        xml_url: "http://antirez.com/rss",
    },
    DefaultFeedWebSource {
        title: "idiallo.com",
        domain: "idiallo.com",
        html_url: "https://idiallo.com",
        xml_url: "https://idiallo.com/feed.rss",
    },
    DefaultFeedWebSource {
        title: "maurycyz.com",
        domain: "maurycyz.com",
        html_url: "https://maurycyz.com",
        xml_url: "https://maurycyz.com/index.xml",
    },
    DefaultFeedWebSource {
        title: "pluralistic.net",
        domain: "pluralistic.net",
        html_url: "https://pluralistic.net",
        xml_url: "https://pluralistic.net/feed/",
    },
    DefaultFeedWebSource {
        title: "shkspr.mobi",
        domain: "shkspr.mobi",
        html_url: "https://shkspr.mobi",
        xml_url: "https://shkspr.mobi/blog/feed/",
    },
    DefaultFeedWebSource {
        title: "lcamtuf.substack.com",
        domain: "lcamtuf.substack.com",
        html_url: "https://lcamtuf.substack.com",
        xml_url: "https://lcamtuf.substack.com/feed",
    },
    DefaultFeedWebSource {
        title: "mitchellh.com",
        domain: "mitchellh.com",
        html_url: "https://mitchellh.com",
        xml_url: "https://mitchellh.com/feed.xml",
    },
    DefaultFeedWebSource {
        title: "dynomight.net",
        domain: "dynomight.net",
        html_url: "https://dynomight.net",
        xml_url: "https://dynomight.net/feed.xml",
    },
    DefaultFeedWebSource {
        title: "xeiaso.net",
        domain: "xeiaso.net",
        html_url: "https://xeiaso.net",
        xml_url: "https://xeiaso.net/blog.rss",
    },
    DefaultFeedWebSource {
        title: "devblogs.microsoft.com/oldnewthing",
        domain: "devblogs.microsoft.com",
        html_url: "https://devblogs.microsoft.com/oldnewthing",
        xml_url: "https://devblogs.microsoft.com/oldnewthing/feed",
    },
    DefaultFeedWebSource {
        title: "righto.com",
        domain: "righto.com",
        html_url: "https://righto.com",
        xml_url: "https://www.righto.com/feeds/posts/default",
    },
    DefaultFeedWebSource {
        title: "lucumr.pocoo.org",
        domain: "lucumr.pocoo.org",
        html_url: "https://lucumr.pocoo.org",
        xml_url: "https://lucumr.pocoo.org/feed.atom",
    },
    DefaultFeedWebSource {
        title: "skyfall.dev",
        domain: "skyfall.dev",
        html_url: "https://skyfall.dev",
        xml_url: "https://skyfall.dev/rss.xml",
    },
    DefaultFeedWebSource {
        title: "garymarcus.substack.com",
        domain: "garymarcus.substack.com",
        html_url: "https://garymarcus.substack.com",
        xml_url: "https://garymarcus.substack.com/feed",
    },
    DefaultFeedWebSource {
        title: "rachelbythebay.com",
        domain: "rachelbythebay.com",
        html_url: "https://rachelbythebay.com",
        xml_url: "https://rachelbythebay.com/w/atom.xml",
    },
    DefaultFeedWebSource {
        title: "overreacted.io",
        domain: "overreacted.io",
        html_url: "https://overreacted.io",
        xml_url: "https://overreacted.io/rss.xml",
    },
    DefaultFeedWebSource {
        title: "timsh.org",
        domain: "timsh.org",
        html_url: "https://timsh.org",
        xml_url: "https://timsh.org/rss/",
    },
    DefaultFeedWebSource {
        title: "johndcook.com",
        domain: "johndcook.com",
        html_url: "https://johndcook.com",
        xml_url: "https://www.johndcook.com/blog/feed/",
    },
    DefaultFeedWebSource {
        title: "gilesthomas.com",
        domain: "gilesthomas.com",
        html_url: "https://gilesthomas.com",
        xml_url: "https://gilesthomas.com/feed/rss.xml",
    },
    DefaultFeedWebSource {
        title: "matklad.github.io",
        domain: "matklad.github.io",
        html_url: "https://matklad.github.io",
        xml_url: "https://matklad.github.io/feed.xml",
    },
    DefaultFeedWebSource {
        title: "evanhahn.com",
        domain: "evanhahn.com",
        html_url: "https://evanhahn.com",
        xml_url: "https://evanhahn.com/feed.xml",
    },
    DefaultFeedWebSource {
        title: "terriblesoftware.org",
        domain: "terriblesoftware.org",
        html_url: "https://terriblesoftware.org",
        xml_url: "https://terriblesoftware.org/feed/",
    },
    DefaultFeedWebSource {
        title: "rakhim.exotext.com",
        domain: "rakhim.exotext.com",
        html_url: "https://rakhim.exotext.com",
        xml_url: "https://rakhim.exotext.com/rss.xml",
    },
    DefaultFeedWebSource {
        title: "joanwestenberg.com",
        domain: "joanwestenberg.com",
        html_url: "https://joanwestenberg.com",
        xml_url: "https://joanwestenberg.com/rss",
    },
    DefaultFeedWebSource {
        title: "xania.org",
        domain: "xania.org",
        html_url: "https://xania.org",
        xml_url: "https://xania.org/feed",
    },
    DefaultFeedWebSource {
        title: "micahflee.com",
        domain: "micahflee.com",
        html_url: "https://micahflee.com",
        xml_url: "https://micahflee.com/feed/",
    },
    DefaultFeedWebSource {
        title: "construction-physics.com",
        domain: "construction-physics.com",
        html_url: "https://construction-physics.com",
        xml_url: "https://www.construction-physics.com/feed",
    },
    DefaultFeedWebSource {
        title: "tedium.co",
        domain: "tedium.co",
        html_url: "https://tedium.co",
        xml_url: "https://feed.tedium.co/",
    },
    DefaultFeedWebSource {
        title: "entropicthoughts.com",
        domain: "entropicthoughts.com",
        html_url: "https://entropicthoughts.com",
        xml_url: "https://entropicthoughts.com/feed.xml",
    },
    DefaultFeedWebSource {
        title: "buttondown.com/hillelwayne",
        domain: "buttondown.com",
        html_url: "https://buttondown.com/hillelwayne",
        xml_url: "https://buttondown.com/hillelwayne/rss",
    },
    DefaultFeedWebSource {
        title: "dwarkesh.com",
        domain: "dwarkesh.com",
        html_url: "https://dwarkesh.com",
        xml_url: "https://www.dwarkeshpatel.com/feed",
    },
    DefaultFeedWebSource {
        title: "borretti.me",
        domain: "borretti.me",
        html_url: "https://borretti.me",
        xml_url: "https://borretti.me/feed.xml",
    },
    DefaultFeedWebSource {
        title: "wheresyoured.at",
        domain: "wheresyoured.at",
        html_url: "https://wheresyoured.at",
        xml_url: "https://www.wheresyoured.at/rss/",
    },
    DefaultFeedWebSource {
        title: "minimaxir.com",
        domain: "minimaxir.com",
        html_url: "https://minimaxir.com",
        xml_url: "https://minimaxir.com/index.xml",
    },
    DefaultFeedWebSource {
        title: "geohot.github.io",
        domain: "geohot.github.io",
        html_url: "https://geohot.github.io",
        xml_url: "https://geohot.github.io/blog/feed.xml",
    },
    DefaultFeedWebSource {
        title: "paulgraham.com",
        domain: "paulgraham.com",
        html_url: "https://paulgraham.com",
        xml_url: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
    },
    DefaultFeedWebSource {
        title: "filfre.net",
        domain: "filfre.net",
        html_url: "https://filfre.net",
        xml_url: "https://www.filfre.net/feed/",
    },
    DefaultFeedWebSource {
        title: "blog.jim-nielsen.com",
        domain: "blog.jim-nielsen.com",
        html_url: "https://blog.jim-nielsen.com",
        xml_url: "https://blog.jim-nielsen.com/feed.xml",
    },
    DefaultFeedWebSource {
        title: "geoffreylitt.com",
        domain: "geoffreylitt.com",
        html_url: "https://geoffreylitt.com",
        xml_url: "https://www.geoffreylitt.com/feed.xml",
    },
    DefaultFeedWebSource {
        title: "eli.thegreenplace.net",
        domain: "eli.thegreenplace.net",
        html_url: "https://eli.thegreenplace.net",
        xml_url: "https://eli.thegreenplace.net/feeds/all.atom.xml",
    },
    DefaultFeedWebSource {
        title: "abortretry.fail",
        domain: "abortretry.fail",
        html_url: "https://abortretry.fail",
        xml_url: "https://www.abortretry.fail/feed",
    },
    // --- Mindfulness, Buddhism, Meditation, Consciousness ---
    DefaultFeedWebSource {
        title: "zenhabits.net",
        domain: "zenhabits.net",
        html_url: "https://zenhabits.net",
        xml_url: "https://zenhabits.net/feed/",
    },
    DefaultFeedWebSource {
        title: "tricycle.org",
        domain: "tricycle.org",
        html_url: "https://tricycle.org",
        xml_url: "https://tricycle.org/feed/",
    },
    DefaultFeedWebSource {
        title: "mindful.org",
        domain: "mindful.org",
        html_url: "https://www.mindful.org",
        xml_url: "https://www.mindful.org/feed/",
    },
    DefaultFeedWebSource {
        title: "lionsroar.com",
        domain: "lionsroar.com",
        html_url: "https://www.lionsroar.com",
        xml_url: "https://www.lionsroar.com/feed/",
    },
    // --- Philosophy, Psychology, Ideas ---
    DefaultFeedWebSource {
        title: "fs.blog",
        domain: "fs.blog",
        html_url: "https://fs.blog",
        xml_url: "https://fs.blog/feed/",
    },
    DefaultFeedWebSource {
        title: "aeon.co",
        domain: "aeon.co",
        html_url: "https://aeon.co",
        xml_url: "https://aeon.co/feed.rss",
    },
    DefaultFeedWebSource {
        title: "psyche.co",
        domain: "psyche.co",
        html_url: "https://psyche.co",
        xml_url: "https://psyche.co/feed",
    },
    DefaultFeedWebSource {
        title: "themarginalian.org",
        domain: "themarginalian.org",
        html_url: "https://www.themarginalian.org",
        xml_url: "https://www.themarginalian.org/feed/",
    },
    // --- Economics, Business, Social Innovation ---
    DefaultFeedWebSource {
        title: "marginalrevolution.com",
        domain: "marginalrevolution.com",
        html_url: "https://marginalrevolution.com",
        xml_url: "https://marginalrevolution.com/feed",
    },
    DefaultFeedWebSource {
        title: "evonomics.com",
        domain: "evonomics.com",
        html_url: "https://evonomics.com",
        xml_url: "https://evonomics.com/feed/",
    },
    // --- AI Workflows, Productivity, Content Creation ---
    DefaultFeedWebSource {
        title: "every.to",
        domain: "every.to",
        html_url: "https://every.to",
        xml_url: "https://every.to/feed.xml",
    },
    DefaultFeedWebSource {
        title: "nesslabs.com",
        domain: "nesslabs.com",
        html_url: "https://nesslabs.com",
        xml_url: "https://nesslabs.com/feed",
    },
    DefaultFeedWebSource {
        title: "oneusefulthing.org",
        domain: "oneusefulthing.org",
        html_url: "https://www.oneusefulthing.org",
        xml_url: "https://www.oneusefulthing.org/feed",
    },
    // --- Science, Interdisciplinary ---
    DefaultFeedWebSource {
        title: "nautil.us",
        domain: "nautil.us",
        html_url: "https://nautil.us",
        xml_url: "https://nautil.us/feed/",
    },
    DefaultFeedWebSource {
        title: "astralcodexten.com",
        domain: "astralcodexten.com",
        html_url: "https://www.astralcodexten.com",
        xml_url: "https://www.astralcodexten.com/feed",
    },
];
