import {createRequire} from 'node:module';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {schnorr} from '@noble/curves/secp256k1.js';
const req=createRequire(import.meta.url),wr=createRequire(req.resolve('wrangler/package.json'));
const {Miniflare}=wr('miniflare'),{build}=wr('esbuild');
const dir=mkdtempSync(join(tmpdir(),'slowclaw-web-test-'));
const origin='https://slowclaw-web.zanynik.chatgpt.site';
const bytes=s=>new TextEncoder().encode(s),hex=b=>Buffer.from(b).toString('hex');
const hash=async b=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof b==='string'?bytes(b):b)));
const secret=new Uint8Array(32);secret[31]=1;
async function sign(path,method,body='',other=secret,time=Math.floor(Date.now()/1000)){
 const pubkey=hex(schnorr.getPublicKey(other));
 const tags=[['u',origin+'/api/session/'+path],['method',method],['payload',await hash(body)],['nonce',crypto.randomUUID()]];
 const id=await hash(JSON.stringify([0,pubkey,time,27235,tags,'']));
 const sig=hex(schnorr.sign(Buffer.from(id,'hex'),other));
 return 'Nostr '+Buffer.from(JSON.stringify({id,pubkey,created_at:time,kind:27235,tags,content:'',sig})).toString('base64');
}
let mf;
try{
 await build({stdin:{contents:"import {handle} from './lib/session-server.ts'; export default {fetch:r=>handle(r,new URL(r.url).pathname.replace('/api/session','').split('/').filter(Boolean))};",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'browser',external:['cloudflare:workers'],outfile:join(dir,'worker.mjs')});
 mf=new Miniflare({modules:true,modulesRoot:dir,rootPath:dir,scriptPath:join(dir,'worker.mjs'),compatibilityDate:'2026-05-15',d1Databases:{DB:'test-db'},r2Buckets:{BUCKET:'test-bucket'}});
 const db=await mf.getD1Database('DB');
 for(const file of ['drizzle/0000_numerous_scorpion.sql','drizzle/0001_icy_longshot.sql'])for(const s of readFileSync(file,'utf8').split('--> statement-breakpoint'))if(s.trim())await db.prepare(s.trim()).run();
 const call=(path='',method='GET',auth='',body)=>mf.dispatchFetch(origin+'/api/session'+(path?'/'+path:''),{method,headers:{Origin:origin,...(auth?{Authorization:auth}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},body});
 let r=await call('','POST');assert.equal(r.status,200);const s=await r.json();
 assert.equal((await call(s.id)).status,401,'browser capability required');
 const body=JSON.stringify({pair:s.pair});const proof=await sign(s.id+'/pair','POST',body);
 r=await call(s.id+'/pair','POST',proof,body);assert.equal(r.status,200);
 assert.equal((await call(s.id+'/pair','POST',proof,body)).status,409,'pair replay rejected');
 const other=new Uint8Array(32);other[31]=2;
 assert.equal((await call(s.id,'GET',await sign(s.id,'GET','',other))).status,403,'different phone denied');
 const snap=JSON.stringify({sealed:'encrypted-placeholder'}),snapAuth=await sign(s.id+'/snapshot','PUT',snap);
 assert.equal((await call(s.id+'/snapshot','PUT',snapAuth,JSON.stringify({sealed:'changed'}))).status,401,'body binding enforced');
 assert.equal((await call(s.id+'/snapshot','PUT',snapAuth,snap)).status,200);
 assert.equal((await call(s.id+'/snapshot','PUT',snapAuth,snap)).status,409,'proof replay rejected');
 assert.equal((await call(s.id,'GET',await sign(s.id,'GET','',secret,1))).status,401,'old proof rejected');
 r=await call(s.id,'GET','Bearer '+s.token);const snapshotState=await r.json();assert.equal(snapshotState.snapshot,'encrypted-placeholder');
 r=await call(s.id+'?after='+encodeURIComponent(snapshotState.revision),'GET','Bearer '+s.token);
 assert.equal((await r.json()).snapshot,undefined,'unchanged snapshot is not retransmitted');
 const editID='c'.repeat(64),editBody=JSON.stringify({id:editID,sealed:'x'.repeat(80)});
 assert.equal((await call(s.id+'/note','POST','Bearer '+s.token,editBody)).status,200);
 assert.equal((await call(s.id+'/note','POST','Bearer '+s.token,editBody)).status,200,'lost enqueue response is idempotent');
 assert.equal((await call(s.id+'/note','POST','Bearer '+s.token,JSON.stringify({id:editID,sealed:'y'.repeat(80)}))).status,409,'operation cannot be replaced');
 assert.equal((await call(s.id+'/note/'+editID,'DELETE','Bearer '+s.token)).status,200);
 assert.equal((await db.prepare('SELECT status FROM journal_edits WHERE id=?').bind(editID).first()).status,'queued','queued operation cannot be deleted');
 const receipt=JSON.stringify({status:'conflict',result:'encrypted-conflict-result'});
 assert.equal((await call(s.id+'/note/'+editID,'POST','Bearer '+s.token,receipt)).status,404,'only paired phone can acknowledge journal saves');
 assert.equal((await call(s.id+'/note/'+editID,'POST',await sign(s.id+'/note/'+editID,'POST',receipt,other),receipt)).status,403,'other identity cannot acknowledge');
 assert.equal((await call(s.id+'/note/'+editID,'POST',await sign(s.id+'/note/'+editID,'POST',receipt),receipt)).status,200);
 const savedReceipt=JSON.stringify({status:'saved',result:'changed-result'});
 assert.equal((await call(s.id+'/note/'+editID,'POST',await sign(s.id+'/note/'+editID,'POST',savedReceipt),savedReceipt)).status,200);
 const editRow=await db.prepare('SELECT * FROM journal_edits WHERE id=?').bind(editID).first();
 assert.equal(editRow.status,'conflict','terminal receipt is immutable');assert.equal(editRow.sealed,'','completed request bytes removed');
 assert.equal((await call(s.id+'/note/'+editID,'DELETE','Bearer '+s.token)).status,200);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM journal_edits').first()).n,0);
 assert.equal((await call(s.id+'/note','POST','Bearer '+s.token,editBody)).status,200);
 const id='a'.repeat(64),meta='encrypted-metadata',file=Buffer.alloc(128,7);
 r=await call(s.id+'/upload','POST','Bearer '+s.token,JSON.stringify({id,meta,bytes:file.length}));assert.equal(r.status,200);
 r=await mf.dispatchFetch(origin+'/api/session/'+s.id+'/file/'+id,{method:'PUT',headers:{Origin:origin,Authorization:'Bearer '+s.token,'Content-Length':String(file.length)},body:file});assert.equal(r.status,200);
 assert.equal((await call(s.id+'/file/'+id,'GET','Bearer '+s.token)).status,404,'browser cannot retrieve phone queue bytes');
 r=await call(s.id+'/file/'+id,'GET',await sign(s.id+'/file/'+id,'GET'));assert.deepEqual(Buffer.from(await r.arrayBuffer()),file);
 assert.equal((await call(s.id+'/file/'+id,'POST',await sign(s.id+'/file/'+id,'POST'),'')).status,200);
 assert.equal(await (await mf.getR2Bucket('BUCKET')).get(s.id+'/'+id),null,'receipt deletes server file');
 r=await call(s.id,'GET','Bearer '+s.token);assert.equal((await r.json()).transfers[0].status,'saved');
 const interrupted='b'.repeat(64);
 assert.equal((await call(s.id+'/upload','POST','Bearer '+s.token,JSON.stringify({id:interrupted,meta,bytes:128}))).status,200);
 assert.equal((await call(s.id+'/file/'+interrupted,'DELETE','Bearer '+s.token)).status,200,'incomplete reservation removed');
 assert.equal((await call(s.id+'/file/'+id,'DELETE','Bearer '+s.token)).status,409,'received file receipt preserved');
 assert.equal((await call(s.id,'DELETE','Bearer '+s.token)).status,200);
 assert.equal((await call(s.id,'GET','Bearer '+s.token)).status,410);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM transfers').first()).n,0);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM proofs').first()).n,0);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM journal_edits').first()).n,0,'logout removes encrypted editor operations');
 r=await call('','POST');const expired=await r.json();await db.prepare('UPDATE sessions SET expires=1 WHERE id=?').bind(expired.id).run();
 assert.equal((await call(expired.id,'GET','Bearer '+expired.token)).status,410);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM sessions').first()).n,0,'expired sessions swept');
 console.log('PASS: pairing, identity isolation, exact request signing, replay/expiry, file delivery, receipts and logout deletion');
}finally{await mf?.dispose();rmSync(dir,{recursive:true,force:true});}
