'use client';
import {useEffect,useRef,useState} from 'react';
import {JournalNotepad,JournalOperation} from '@/components/journal-notepad';
import QRCode from 'qrcode';
import {JournalThoughts} from '@/components/journal-thoughts';
import {UnitGroup} from '@/lib/journal-units';
import {BookOpen,Feather,Radio,Upload,Smartphone,LockKeyhole,LogOut,RefreshCw,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {keyFrom,seal,unseal,toBase64,fromBase64} from '@/lib/sealed';
type Session={id:string;token:string;pair:string;key:string;expires:number};
type Entry={id:string;title?:string;text:string;date?:string;author?:string;kind?:string;url?:string;revision?:string};
type Snapshot={unitsVersion?:number;unitGroups?:UnitGroup[];unitRevisions?:Record<string,string>;index?:Entry[];editorVersion?:number;journals:Entry[];creations:Entry[];pulse:Entry[];syncedAt:number};
type Transfer={id:string;meta:string;bytes:number;status:string;name?:string};
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
const empty:Snapshot={journals:[],creations:[],pulse:[],syncedAt:0};
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[paired,setPaired]=useState(false),[qr,setQr]=useState(''),[data,setData]=useState(empty),[transfers,setTransfers]=useState<Transfer[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ending,setEnding]=useState(false),[tab,setTab]=useState('journals'),[working,setWorking]=useState(''),[lastSeen,setLastSeen]=useState(0);
 const [operations,setOperations]=useState<JournalOperation[]>([]);
 const current=useRef<Session|null>(null),polling=useRef(false),revision=useRef(''),fileInput=useRef<HTMLInputElement>(null);
 function forget(){const id=current.current?.id;if(id){sessionStorage.removeItem('slowclaw.web.drafts.'+id);sessionStorage.removeItem('slowclaw.web.units.'+id);}setOperations([]);revision.current='';sessionStorage.removeItem('slowclaw.web.session');current.current=null;setSession(null);setPaired(false);setQr('');setData(empty);setTransfers([]);setLastSeen(0);}
 async function api(s:Session,path='',options:RequestInit={}){const r=await fetch('/api/session/'+s.id+path,{...options,cache:'no-store',headers:{Authorization:'Bearer '+s.token,...options.headers}});const value:any=await r.json();if(!r.ok){if(r.status===410&&current.current?.id===s.id)forget();throw Error(value.error||'Please retry.');}return value;}
 async function refresh(s:Session){if(polling.current)return;polling.current=true;try{const next=await api(s,revision.current?'?after='+encodeURIComponent(revision.current):'');if(current.current?.id!==s.id)return;const key=await keyFrom(s.key);setOperations(next.edits||[]);setPaired(next.paired);setLastSeen(next.updated||0);if(next.paired){setQr('');s={...s,pair:'',expires:next.expires};current.current=s;setSession(s);sessionStorage.setItem('slowclaw.web.session',JSON.stringify(s));}
  if(next.snapshot){const snapshot=JSON.parse(new TextDecoder().decode(await unseal(key,fromBase64(next.snapshot),s.id+'/snapshot')));if(current.current?.id===s.id){setData(snapshot);revision.current=next.revision||'';}}
  const rows=await Promise.all(next.transfers.map(async(t:Transfer)=>({...t,...JSON.parse(new TextDecoder().decode(await unseal(key,fromBase64(t.meta),s.id+'/'+t.id+'/meta')))})));
  if(current.current?.id===s.id)setTransfers(rows);
 }catch(e){setError((e as Error).message);}finally{polling.current=false;}}
 useEffect(()=>{try{const s=JSON.parse(sessionStorage.getItem('slowclaw.web.session')||'null');if(s&&s.expires>Date.now()/1000){current.current=s;setSession(s);void refresh(s);}else forget();}catch{forget();}},[]);
 useEffect(()=>{if(!session)return;let disposed=false;if(session.pair){const value=location.origin+'/pair#'+new URLSearchParams({id:session.id,pair:session.pair,key:session.key});void QRCode.toDataURL(value,{width:300,margin:2,errorCorrectionLevel:'M'}).then(s=>{if(!disposed)setQr(s);});}const timer=setInterval(()=>{const s=current.current;if(!s)return;if(s.expires<=Date.now()/1000){forget();setError('Session expired. Scan a fresh code.');}else void refresh(s);},4000);return()=>{disposed=true;clearInterval(timer);};},[session?.id,session?.pair]);
 // A read-only tool exposes transfer status, never journal text or credentials.
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const c=new AbortController();try{context.registerTool({name:'read_transfer_status',description:'Read the visible phone transfer status; does not upload or expose private content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {paired,pending:transfers.filter(t=>t.status!=='saved').length,saved:transfers.filter(t=>t.status==='saved').length};}},{signal:c.signal});}catch{}return()=>c.abort();},[paired,transfers]);
 async function start(){setBusy(true);setError('');try{const r=await fetch('/api/session',{method:'POST'});const v:any=await r.json();if(!r.ok)throw Error(v.error);const s={...v,key:random()};current.current=s;setSession(s);sessionStorage.setItem('slowclaw.web.session',JSON.stringify(s));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){if(!session)return;setBusy(true);try{await api(session,'',{method:'DELETE'});forget();setEnding(false);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(files:FileList|null){const s=current.current;if(!s||!files)return;setBusy(true);setError('');try{const key=await keyFrom(s.key);for(const f of Array.from(files)){if(current.current?.id!==s.id)throw Error('Session ended.');if(!/\.(txt|md|m4a|mp3|wav|aac|aiff|caf|flac)$/i.test(f.name))throw Error(f.name+': choose a text journal or audio file.');if(/\.(txt|md)$/i.test(f.name)&&f.size>1000000)throw Error(f.name+': text journals can be up to 1 MB. Split longer files first.');if(f.size>50*1024*1024||f.size===0)throw Error(f.name+': files must be between 1 byte and 50 MB.');setWorking('Encrypting '+f.name);const id=random(),meta=toBase64(await seal(key,new TextEncoder().encode(JSON.stringify({name:f.name.slice(0,240),type:/\.(txt|md)$/i.test(f.name)?'text':'audio',modified:f.lastModified})),s.id+'/'+id+'/meta'));const bytes=await seal(key,new Uint8Array(await f.arrayBuffer()),s.id+'/'+id+'/file');await api(s,'/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,meta,bytes:bytes.length})});setWorking('Sending '+f.name);await api(s,'/file/'+id,{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:bytes as unknown as BodyInit});await refresh(s);}}catch(e){setError((e as Error).message+' You can select the original file again to retry.');}finally{setBusy(false);setWorking('');if(fileInput.current)fileInput.current.value='';}}
 async function removeIncomplete(id:string){const s=current.current;if(!s)return;try{await api(s,'/file/'+id,{method:'DELETE'});await refresh(s);}catch(e){setError((e as Error).message);}}
 const pending=transfers.filter(t=>t.status!=='saved').length+operations.filter(o=>o.status==='queued').length;
 return <main className="shell"><header className="top"><a className="brand" href="/">slowclaw<span>web</span></a><span className="quiet desktop">A little more room for your thoughts.</span>{!paired&&<a className="about-link" href="#about-slowclaw">About</a>}<div className="top-actions">{paired&&<span className="session-dot">Phone paired</span>}{session&&<Button variant="ghost" disabled={busy} onClick={()=>setEnding(true)}><LogOut size={16}/>Log out</Button>}</div></header>
 {error&&<div role="alert" className="error">{error}<Button variant="ghost" size="sm" onClick={()=>setError('')}>Dismiss</Button></div>}
 {!paired?<section className="pair-layout"><div className="intro"><p className="eyebrow">YOUR PHONE. A BIGGER PAGE.</p><h1>Pick up<br/>your train<br/><em>of thought.</em></h1><p className="lead">SlowClaw is a quiet place to journal, understand what matters to you, and discover ideas through your own reflections. Write here, revisit an entry, or edit a transcript. Your words sync back to your phone as you write.</p><div className="privacy-note"><LockKeyhole size={19}/><p>Your Nostr key stays on your phone. This is a temporary, encrypted session—not a cloud backup.</p></div></div><div className="pair-card"><Smartphone size={26}/><h2>Connect your SlowClaw</h2><p>On your iPhone, open <strong>Profile → SlowClaw Web</strong>, then scan this code.</p><div className="qr-space">{qr?<img src={qr} width={280} height={280} alt="Scan with SlowClaw to approve this browser session"/>:<div><BookOpen size={44}/><p>One scan. Your journals, here.</p><Button onClick={start} disabled={busy||!!session}>{busy?'Preparing…':session?'Waiting for phone…':'Show pairing code'}</Button></div>}</div><p className="caption">Approve the connection on your phone.<br/>Codes expire after 5 minutes. Sessions last up to 24 hours.</p></div></section>:<>
 <section className="workspace-heading"><div><p className="eyebrow">YOUR JOURNAL WORKSPACE</p><h1>Room to reflect.</h1><p className="quiet">{lastSeen?'Last synced '+new Date(lastSeen*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Waiting for your phone to send recent data…'}</p></div><Button variant="outline" onClick={()=>session&&refresh(session)}><RefreshCw size={16}/>Refresh</Button></section>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="nav-tabs" variant="line"><TabsTrigger value="journals"><BookOpen size={17}/>Journals <small>{(data.index||data.journals).length}</small></TabsTrigger><TabsTrigger value="thoughts"><Feather size={17}/>Your thoughts</TabsTrigger><TabsTrigger value="creations"><Feather size={17}/>Moments <small>{data.creations.length}</small></TabsTrigger><TabsTrigger value="pulse"><Radio size={17}/>Pulse</TabsTrigger><TabsTrigger value="uploads"><Upload size={17}/>Send to phone {pending>0&&<small>{pending}</small>}</TabsTrigger></TabsList>
 <TabsContent value="journals" forceMount className="data-[state=inactive]:hidden">{session&&<JournalNotepad session={session} index={data.index||data.journals} recent={data.journals} operations={operations} api={api} enabled={data.editorVersion===1}/>}</TabsContent>
 <TabsContent value="thoughts" forceMount className="data-[state=inactive]:hidden">{session&&<JournalThoughts session={session} index={data.index||data.journals} recent={data.journals} groups={data.unitGroups||[]} revisions={data.unitRevisions||{}} operations={operations} enabled={data.unitsVersion===1} api={api}/>}</TabsContent>
 {(['creations','pulse'] as const).map(section=><TabsContent key={section} value={section}><div className={section==='creations'?'cards':'reading-list'}>{data[section].length===0?<div className="empty"><BookOpen size={30}/><h2>{lastSeen?'Nothing here yet.':'Your phone is preparing this week.'}</h2><p>{section==='creations'?'Moments found in your recent journals will appear here as text cards.':section==='pulse'?'Refresh Pulse on your phone to bring its current feed here.':'Keep SlowClaw open on your phone to sync recent journals.'}</p></div>:data[section].map((entry,i)=><article key={entry.id} className={'entry '+(section==='creations'?'quote':'')}><div className="entry-meta"><span>{entry.author||entry.kind||('PULSE')}</span><span>{entry.date?new Date(entry.date).toLocaleDateString([],{month:'short',day:'numeric'}):String(i+1).padStart(2,'0')}</span></div>{entry.title&&<h2>{entry.title}</h2>}<p className="entry-body">{entry.text}</p>{section==='pulse'&&entry.url?.startsWith('https://')&&<a href={entry.url} target="_blank" rel="noopener noreferrer" className="read-link">Open post <ArrowUpRight size={15}/></a>}</article>)}</div></TabsContent>)}
 <TabsContent value="uploads"><section className="upload-layout"><div className="upload-box"><Upload size={30}/><h2>Bring your older thoughts along.</h2><p>Add text journals or recordings from your laptop. Your phone imports them into its journal and transcribes supported audio on device.</p><input ref={fileInput} className="file-input" id="files" type="file" multiple accept=".txt,.md,.m4a,.mp3,.wav,.aac,.aiff,.caf,.flac" disabled={busy} onChange={e=>void upload(e.target.files)}/><Button disabled={busy} onClick={()=>fileInput.current?.click()}>{busy?'Sending…':'Choose files'}</Button><p className="caption">Text up to 1 MB · audio up to 50 MB · 250 MB waiting at a time<br/>Keep the phone app open to receive. Originals stay on your laptop.</p>{working&&<p role="status">{working}</p>}</div><div><h2 className="transfer-title">Transfers</h2>{transfers.length===0?<p className="quiet">Files you send will appear here.</p>:transfers.map(t=><div className="transfer" key={t.id}><div><strong>{t.name||'Encrypted file'}</strong><small>{(t.bytes/1024/1024).toFixed(1)} MB</small></div><span className={t.status==='saved'?'saved':'waiting'}>{t.status==='saved'?'Saved on phone':t.status==='ready'?'Waiting for phone':'Upload incomplete'}{t.status==='pending'&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void removeIncomplete(t.id)}>Remove</Button>}</span></div>)}</div></section></TabsContent></Tabs>
 <footer><LockKeyhole size={15}/><p>Older notes and transcripts load when you select them. Recent text is shared with a size limit. Log out to delete this session’s server copy. Imports marked “Saved on phone” stay on your phone. Sync resumes when the phone app is open.</p></footer></>}
 {!paired&&<section id="about-slowclaw" className="about-slowclaw" aria-labelledby="about-title"><p className="eyebrow">A QUIETER DIGITAL LIFE</p><h2 id="about-title">Journal first. Structure later.</h2><p className="about-lead">Start with what is on your mind. SlowClaw helps you return to it with a little more clarity.</p><div className="about-grid"><article><BookOpen size={22}/><h3>Make room to reflect.</h3><p>Capture a thought in text, audio, or video on your iPhone. On the web, a simple notepad gives your words more room.</p></article><article><Feather size={22}/><h3>Notice what connects.</h3><p>Bring related passages together into grouped thoughts, or revisit a moment worth keeping. Your journals remain the source.</p></article><article><Radio size={22}/><h3>Follow your curiosity.</h3><p>Let your reflections guide what you read. Create from the ideas that matter, and choose what you share.</p></article></div><div className="about-bottom"><p><LockKeyhole size={16}/>Local intelligence. Encrypted browser sessions. Your phone keeps the originals.</p><a href="https://github.com/zanynik/slowclaw.social" target="_blank" rel="noopener noreferrer">Explore the open source project <ArrowUpRight size={15}/></a></div></section>}
 <AlertDialog open={ending} onOpenChange={setEnding}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>End this web session?</AlertDialogTitle><AlertDialogDescription>{pending?`${pending} transfer${pending===1?' is':'s are'} not saved on your phone yet. Logging out deletes pending copies and browser drafts, including unsynced journal edits. Wait until your editor says “Saved on phone”, or copy your text before logging out.`:'Browser drafts, recent data and encrypted uploads will be deleted from this web session. Unsynced journal edits will be lost. Check that your editor says “Saved on phone” before logging out. Anything already saved on your phone stays there.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep session</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void logout();}}>Log out & delete session</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
