#!/usr/bin/env ruby
# ios-add-speech-plugin.rb — Xcode integration for the iOS SFSpeechRecognizer
# bridge.
#
# Copies `web/src-tauri/ios/SpeechTranscriber/SpeechTranscriber.swift` into the
# generated Xcode project directory and adds it to the iOS app target's
# "Compile Sources" build phase, so the Swift `@_cdecl("slowclaw_transcribe_audio")`
# symbol is compiled and linked into the IPA.
#
# Why a copy + SOURCE_ROOT reference:
#   - The Swift source of truth lives in `web/src-tauri/ios/` (version
#     controlled). The generated Xcode project lives in
#     `web/src-tauri/gen/apple/` (gitignored, regenerated by `tauri ios init`).
#   - The file reference uses `source_tree = SOURCE_ROOT`, which Xcode
#     resolves to the directory containing the .xcodeproj
#     (`web/src-tauri/gen/apple`). This is deterministic and does NOT depend
#     on the main group's path configuration, which varies across Tauri
#     versions and is unsafe to assume.
#   - Copying the file next to the project avoids `..` relative paths in the
#     pbxproj, which are flaky across Xcode versions.
#
# Idempotent: safe to re-run. Re-running refreshes the copy from the canonical
# source, so edits to `SpeechTranscriber.swift` propagate on the next run.
#
# Prerequisites:
#   - Run `npm run tauri -- ios init --ci --skip-targets-install` from `web/`
#     once (generates `web/src-tauri/gen/apple/` with the Xcode project).
#   - `gem install xcodeproj` (Ruby tooling for editing .pbxproj). On GitHub
#     macos runners: `sudo gem install xcodeproj`.
#
# Usage (from the repo root):
#   ruby scripts/ios-add-speech-plugin.rb

require "fileutils"
require "xcodeproj"

REPO_ROOT = File.expand_path("..", __dir__)
APPLE_DIR = File.join(REPO_ROOT, "web/src-tauri/gen/apple")
CANONICAL_SWIFT = File.join(REPO_ROOT, "web/src-tauri/ios/SpeechTranscriber/SpeechTranscriber.swift")

# Path of the copied file relative to the .xcodeproj directory (SOURCE_ROOT).
COPIED_REL_PATH = "SpeechTranscriber/SpeechTranscriber.swift"
COPIED_ABS_PATH = File.join(APPLE_DIR, COPIED_REL_PATH)
FILE_DISPLAY_NAME = "SpeechTranscriber.swift"

def fail(message)
  warn "error: #{message}"
  exit 1
end

unless Dir.exist?(APPLE_DIR)
  fail(
    "#{APPLE_DIR} does not exist. From the `web/` directory, run:\n" \
    "    npm run tauri -- ios init --ci --skip-targets-install\n" \
    "then re-run this script."
  )
end

unless File.exist?(CANONICAL_SWIFT)
  fail("Swift source not found at #{CANONICAL_SWIFT}")
end

# Refresh the copy so the project always tracks the canonical source.
FileUtils.mkdir_p(File.dirname(COPIED_ABS_PATH))
FileUtils.cp(CANONICAL_SWIFT, COPIED_ABS_PATH)

project_paths = Dir.glob(File.join(APPLE_DIR, "*.xcodeproj"))
if project_paths.empty?
  fail("No .xcodeproj found under #{APPLE_DIR}.")
elsif project_paths.length > 1
  warn "warning: multiple .xcodeproj files found; using #{project_paths.first}"
end
project_path = project_paths.first

project = Xcodeproj::Project.open(project_path)

# Locate the main app target (the one whose product type is an application).
app_target = project.targets.find { |t| t.product_type == "com.apple.product-type.application" }
fail("Could not find an application target in #{project_path}") unless app_target

# Attach the file reference to the main group so it shows up in the Xcode
# navigator. The reference's physical location is SOURCE_ROOT-relative
# (deterministic), independent of the group's own path.
parent_group = project.main_group

existing_ref = parent_group.files.find do |f|
  f.respond_to?(:source_tree) && f.source_tree == "SOURCE_ROOT" && f.path == COPIED_REL_PATH
end

if existing_ref
  file_ref = existing_ref
  status = "already present"
else
  file_ref = parent_group.new_reference(COPIED_REL_PATH)
  file_ref.source_tree = "SOURCE_ROOT"
  file_ref.name = FILE_DISPLAY_NAME
  status = "added"
end

already_in_build_phase = app_target.source_build_phase.files_references.include?(file_ref)
unless already_in_build_phase
  app_target.source_build_phase.add_file_reference(file_ref, true)
end

project.save

puts "SpeechTranscriber.swift: #{status} (copy refreshed at #{COPIED_REL_PATH})."
puts "Target: '#{app_target.name}' in #{File.basename(project_path)}."
puts "Build phase: #{already_in_build_phase ? 'already linked' : 'added to Compile Sources'}."
