// feed_catalog.zig — the default Reads feed catalog.
//
// Ported 1:1 from src/gateway/feed_web_sources.rs (DEFAULT_FEED_WEB_SOURCES)
// so the iOS app reads the SAME sources as the reference app. The web app
// fetches these server-side via the Rust gateway; the iOS app (SwiftUI + Zig,
// no embedded gateway) fetches each xml_url client-side via URLSession and
// parses+ranks them through rss_parser + feeds_ranking in this Zig core.
//
// 114 sources. Update in lockstep with the Rust catalog when it changes.

const std = @import("std");

pub const FeedSource = struct {
    title: []const u8,
    domain: []const u8,
    html_url: []const u8,
    xml_url: []const u8,
};

pub const DEFAULT_FEED_SOURCES: []const FeedSource = &[_]FeedSource{
    .{ .title = "simonwillison.net", .domain = "simonwillison.net", .html_url = "https://simonwillison.net", .xml_url = "https://simonwillison.net/atom/everything/" },
    .{ .title = "jeffgeerling.com", .domain = "jeffgeerling.com", .html_url = "https://jeffgeerling.com", .xml_url = "https://www.jeffgeerling.com/blog.xml" },
    .{ .title = "seangoedecke.com", .domain = "seangoedecke.com", .html_url = "https://seangoedecke.com", .xml_url = "https://www.seangoedecke.com/rss.xml" },
    .{ .title = "krebsonsecurity.com", .domain = "krebsonsecurity.com", .html_url = "https://krebsonsecurity.com", .xml_url = "https://krebsonsecurity.com/feed/" },
    .{ .title = "daringfireball.net", .domain = "daringfireball.net", .html_url = "https://daringfireball.net", .xml_url = "https://daringfireball.net/feeds/main" },
    .{ .title = "ericmigi.com", .domain = "ericmigi.com", .html_url = "https://ericmigi.com", .xml_url = "https://ericmigi.com/rss.xml" },
    .{ .title = "antirez.com", .domain = "antirez.com", .html_url = "http://antirez.com", .xml_url = "http://antirez.com/rss" },
    .{ .title = "idiallo.com", .domain = "idiallo.com", .html_url = "https://idiallo.com", .xml_url = "https://idiallo.com/feed.rss" },
    .{ .title = "maurycyz.com", .domain = "maurycyz.com", .html_url = "https://maurycyz.com", .xml_url = "https://maurycyz.com/index.xml" },
    .{ .title = "pluralistic.net", .domain = "pluralistic.net", .html_url = "https://pluralistic.net", .xml_url = "https://pluralistic.net/feed/" },
    .{ .title = "shkspr.mobi", .domain = "shkspr.mobi", .html_url = "https://shkspr.mobi", .xml_url = "https://shkspr.mobi/blog/feed/" },
    .{ .title = "lcamtuf.substack.com", .domain = "lcamtuf.substack.com", .html_url = "https://lcamtuf.substack.com", .xml_url = "https://lcamtuf.substack.com/feed" },
    .{ .title = "mitchellh.com", .domain = "mitchellh.com", .html_url = "https://mitchellh.com", .xml_url = "https://mitchellh.com/feed.xml" },
    .{ .title = "dynomight.net", .domain = "dynomight.net", .html_url = "https://dynomight.net", .xml_url = "https://dynomight.net/feed.xml" },
    .{ .title = "xeiaso.net", .domain = "xeiaso.net", .html_url = "https://xeiaso.net", .xml_url = "https://xeiaso.net/blog.rss" },
    .{ .title = "devblogs.microsoft.com/oldnewthing", .domain = "devblogs.microsoft.com", .html_url = "https://devblogs.microsoft.com/oldnewthing", .xml_url = "https://devblogs.microsoft.com/oldnewthing/feed" },
    .{ .title = "righto.com", .domain = "righto.com", .html_url = "https://righto.com", .xml_url = "https://www.righto.com/feeds/posts/default" },
    .{ .title = "lucumr.pocoo.org", .domain = "lucumr.pocoo.org", .html_url = "https://lucumr.pocoo.org", .xml_url = "https://lucumr.pocoo.org/feed.atom" },
    .{ .title = "skyfall.dev", .domain = "skyfall.dev", .html_url = "https://skyfall.dev", .xml_url = "https://skyfall.dev/rss.xml" },
    .{ .title = "garymarcus.substack.com", .domain = "garymarcus.substack.com", .html_url = "https://garymarcus.substack.com", .xml_url = "https://garymarcus.substack.com/feed" },
    .{ .title = "rachelbythebay.com", .domain = "rachelbythebay.com", .html_url = "https://rachelbythebay.com", .xml_url = "https://rachelbythebay.com/w/atom.xml" },
    .{ .title = "overreacted.io", .domain = "overreacted.io", .html_url = "https://overreacted.io", .xml_url = "https://overreacted.io/rss.xml" },
    .{ .title = "timsh.org", .domain = "timsh.org", .html_url = "https://timsh.org", .xml_url = "https://timsh.org/rss/" },
    .{ .title = "johndcook.com", .domain = "johndcook.com", .html_url = "https://johndcook.com", .xml_url = "https://www.johndcook.com/blog/feed/" },
    .{ .title = "gilesthomas.com", .domain = "gilesthomas.com", .html_url = "https://gilesthomas.com", .xml_url = "https://gilesthomas.com/feed/rss.xml" },
    .{ .title = "matklad.github.io", .domain = "matklad.github.io", .html_url = "https://matklad.github.io", .xml_url = "https://matklad.github.io/feed.xml" },
    .{ .title = "evanhahn.com", .domain = "evanhahn.com", .html_url = "https://evanhahn.com", .xml_url = "https://evanhahn.com/feed.xml" },
    .{ .title = "terriblesoftware.org", .domain = "terriblesoftware.org", .html_url = "https://terriblesoftware.org", .xml_url = "https://terriblesoftware.org/feed/" },
    .{ .title = "rakhim.exotext.com", .domain = "rakhim.exotext.com", .html_url = "https://rakhim.exotext.com", .xml_url = "https://rakhim.exotext.com/rss.xml" },
    .{ .title = "joanwestenberg.com", .domain = "joanwestenberg.com", .html_url = "https://joanwestenberg.com", .xml_url = "https://joanwestenberg.com/rss" },
    .{ .title = "xania.org", .domain = "xania.org", .html_url = "https://xania.org", .xml_url = "https://xania.org/feed" },
    .{ .title = "micahflee.com", .domain = "micahflee.com", .html_url = "https://micahflee.com", .xml_url = "https://micahflee.com/feed/" },
    .{ .title = "construction-physics.com", .domain = "construction-physics.com", .html_url = "https://construction-physics.com", .xml_url = "https://www.construction-physics.com/feed" },
    .{ .title = "tedium.co", .domain = "tedium.co", .html_url = "https://tedium.co", .xml_url = "https://feed.tedium.co/" },
    .{ .title = "entropicthoughts.com", .domain = "entropicthoughts.com", .html_url = "https://entropicthoughts.com", .xml_url = "https://entropicthoughts.com/feed.xml" },
    .{ .title = "buttondown.com/hillelwayne", .domain = "buttondown.com", .html_url = "https://buttondown.com/hillelwayne", .xml_url = "https://buttondown.com/hillelwayne/rss" },
    .{ .title = "dwarkesh.com", .domain = "dwarkesh.com", .html_url = "https://dwarkesh.com", .xml_url = "https://www.dwarkeshpatel.com/feed" },
    .{ .title = "borretti.me", .domain = "borretti.me", .html_url = "https://borretti.me", .xml_url = "https://borretti.me/feed.xml" },
    .{ .title = "wheresyoured.at", .domain = "wheresyoured.at", .html_url = "https://wheresyoured.at", .xml_url = "https://www.wheresyoured.at/rss/" },
    .{ .title = "minimaxir.com", .domain = "minimaxir.com", .html_url = "https://minimaxir.com", .xml_url = "https://minimaxir.com/index.xml" },
    .{ .title = "geohot.github.io", .domain = "geohot.github.io", .html_url = "https://geohot.github.io", .xml_url = "https://geohot.github.io/blog/feed.xml" },
    .{ .title = "paulgraham.com", .domain = "paulgraham.com", .html_url = "https://paulgraham.com", .xml_url = "http://www.aaronsw.com/2002/feeds/pgessays.rss" },
    .{ .title = "filfre.net", .domain = "filfre.net", .html_url = "https://filfre.net", .xml_url = "https://www.filfre.net/feed/" },
    .{ .title = "blog.jim-nielsen.com", .domain = "blog.jim-nielsen.com", .html_url = "https://blog.jim-nielsen.com", .xml_url = "https://blog.jim-nielsen.com/feed.xml" },
    .{ .title = "geoffreylitt.com", .domain = "geoffreylitt.com", .html_url = "https://geoffreylitt.com", .xml_url = "https://www.geoffreylitt.com/feed.xml" },
    .{ .title = "eli.thegreenplace.net", .domain = "eli.thegreenplace.net", .html_url = "https://eli.thegreenplace.net", .xml_url = "https://eli.thegreenplace.net/feeds/all.atom.xml" },
    .{ .title = "abortretry.fail", .domain = "abortretry.fail", .html_url = "https://abortretry.fail", .xml_url = "https://www.abortretry.fail/feed" },
    .{ .title = "zenhabits.net", .domain = "zenhabits.net", .html_url = "https://zenhabits.net", .xml_url = "https://zenhabits.net/feed/" },
    .{ .title = "tricycle.org", .domain = "tricycle.org", .html_url = "https://tricycle.org", .xml_url = "https://tricycle.org/feed/" },
    .{ .title = "mindful.org", .domain = "mindful.org", .html_url = "https://www.mindful.org", .xml_url = "https://www.mindful.org/feed/" },
    .{ .title = "lionsroar.com", .domain = "lionsroar.com", .html_url = "https://www.lionsroar.com", .xml_url = "https://www.lionsroar.com/feed/" },
    .{ .title = "fs.blog", .domain = "fs.blog", .html_url = "https://fs.blog", .xml_url = "https://fs.blog/feed/" },
    .{ .title = "aeon.co", .domain = "aeon.co", .html_url = "https://aeon.co", .xml_url = "https://aeon.co/feed.rss" },
    .{ .title = "psyche.co", .domain = "psyche.co", .html_url = "https://psyche.co", .xml_url = "https://psyche.co/feed" },
    .{ .title = "themarginalian.org", .domain = "themarginalian.org", .html_url = "https://www.themarginalian.org", .xml_url = "https://www.themarginalian.org/feed/" },
    .{ .title = "marginalrevolution.com", .domain = "marginalrevolution.com", .html_url = "https://marginalrevolution.com", .xml_url = "https://marginalrevolution.com/feed" },
    .{ .title = "evonomics.com", .domain = "evonomics.com", .html_url = "https://evonomics.com", .xml_url = "https://evonomics.com/feed/" },
    .{ .title = "every.to", .domain = "every.to", .html_url = "https://every.to", .xml_url = "https://every.to/feed.xml" },
    .{ .title = "nesslabs.com", .domain = "nesslabs.com", .html_url = "https://nesslabs.com", .xml_url = "https://nesslabs.com/feed" },
    .{ .title = "oneusefulthing.org", .domain = "oneusefulthing.org", .html_url = "https://www.oneusefulthing.org", .xml_url = "https://www.oneusefulthing.org/feed" },
    .{ .title = "nautil.us", .domain = "nautil.us", .html_url = "https://nautil.us", .xml_url = "https://nautil.us/feed/" },
    .{ .title = "astralcodexten.com", .domain = "astralcodexten.com", .html_url = "https://www.astralcodexten.com", .xml_url = "https://www.astralcodexten.com/feed" },
    .{ .title = "Hacker News", .domain = "news.ycombinator.com", .html_url = "https://news.ycombinator.com", .xml_url = "https://hnrss.org/frontpage" },
    .{ .title = "YouTube — Veritasium", .domain = "youtube.com-veritasium", .html_url = "https://www.youtube.com/@veritasium", .xml_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA" },
    .{ .title = "YouTube — Kurzgesagt", .domain = "youtube.com-kurzgesagt", .html_url = "https://www.youtube.com/@kurzgesagt", .xml_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q" },
    .{ .title = "YouTube — Lex Fridman", .domain = "youtube.com-lex-fridman", .html_url = "https://www.youtube.com/@lexfridman", .xml_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA" },
    .{ .title = "YouTube — Linus Tech Tips", .domain = "youtube.com-linus-tech-tips", .html_url = "https://www.youtube.com/@LinusTechTips", .xml_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw" },
    .{ .title = "utcc.utoronto.ca/~cks", .domain = "utcc.utoronto.ca/~cks", .html_url = "https://utcc.utoronto.ca/~cks", .xml_url = "https://utcc.utoronto.ca/~cks/space/blog/?atom" },
    .{ .title = "The Old New Thing", .domain = "devblogs.microsoft.com/oldnewthing", .html_url = "https://devblogs.microsoft.com/oldnewthing", .xml_url = "https://devblogs.microsoft.com/oldnewthing/feed" },
    .{ .title = "derekthompson.org", .domain = "derekthompson.org", .html_url = "https://derekthompson.org", .xml_url = "https://www.theatlantic.com/feed/author/derek-thompson/" },
    .{ .title = "nesbitt.io", .domain = "nesbitt.io", .html_url = "https://nesbitt.io", .xml_url = "https://nesbitt.io/feed.xml" },
    .{ .title = "susam.net", .domain = "susam.net", .html_url = "https://susam.net", .xml_url = "https://susam.net/feed.xml" },
    .{ .title = "buttondown.com/hillelwayne", .domain = "buttondown.com/hillelwayne", .html_url = "https://buttondown.com/hillelwayne", .xml_url = "https://buttondown.com/hillelwayne/rss" },
    .{ .title = "jayd.ml", .domain = "jayd.ml", .html_url = "https://jayd.ml", .xml_url = "https://jayd.ml/feed.xml" },
    .{ .title = "dfarq.homeip.net", .domain = "dfarq.homeip.net", .html_url = "https://dfarq.homeip.net", .xml_url = "https://dfarq.homeip.net/feed/" },
    .{ .title = "jyn.dev", .domain = "jyn.dev", .html_url = "https://jyn.dev", .xml_url = "https://jyn.dev/atom.xml" },
    .{ .title = "downtowndougbrown.com", .domain = "downtowndougbrown.com", .html_url = "https://downtowndougbrown.com", .xml_url = "https://www.downtowndougbrown.com/feed/" },
    .{ .title = "brutecat.com", .domain = "brutecat.com", .html_url = "https://brutecat.com", .xml_url = "https://brutecat.com/rss.xml" },
    .{ .title = "fabiensanglard.net", .domain = "fabiensanglard.net", .html_url = "https://fabiensanglard.net", .xml_url = "https://fabiensanglard.net/rss.xml" },
    .{ .title = "oldvcr.blogspot.com", .domain = "oldvcr.blogspot.com", .html_url = "https://oldvcr.blogspot.com", .xml_url = "https://oldvcr.blogspot.com/feeds/posts/default" },
    .{ .title = "bogdanthegeek.github.io", .domain = "bogdanthegeek.github.io", .html_url = "https://bogdanthegeek.github.io", .xml_url = "https://bogdanthegeek.github.io/blog/index.xml" },
    .{ .title = "hugotunius.se", .domain = "hugotunius.se", .html_url = "https://hugotunius.se", .xml_url = "https://hugotunius.se/feed.xml" },
    .{ .title = "gwern.net", .domain = "gwern.net", .html_url = "https://gwern.net", .xml_url = "https://gwern.substack.com/feed" },
    .{ .title = "berthub.eu", .domain = "berthub.eu", .html_url = "https://berthub.eu", .xml_url = "https://berthub.eu/articles/index.xml" },
    .{ .title = "chadnauseam.com", .domain = "chadnauseam.com", .html_url = "https://chadnauseam.com", .xml_url = "https://chadnauseam.com/rss.xml" },
    .{ .title = "simone.org", .domain = "simone.org", .html_url = "https://simone.org", .xml_url = "https://simone.org/feed/" },
    .{ .title = "it-notes.dragas.net", .domain = "it-notes.dragas.net", .html_url = "https://it-notes.dragas.net", .xml_url = "https://it-notes.dragas.net/feed/" },
    .{ .title = "beej.us", .domain = "beej.us", .html_url = "https://beej.us", .xml_url = "https://beej.us/blog/rss.xml" },
    .{ .title = "hey.paris", .domain = "hey.paris", .html_url = "https://hey.paris", .xml_url = "https://hey.paris/index.xml" },
    .{ .title = "danielwirtz.com", .domain = "danielwirtz.com", .html_url = "https://danielwirtz.com", .xml_url = "https://danielwirtz.com/rss.xml" },
    .{ .title = "matduggan.com", .domain = "matduggan.com", .html_url = "https://matduggan.com", .xml_url = "https://matduggan.com/rss/" },
    .{ .title = "refactoringenglish.com", .domain = "refactoringenglish.com", .html_url = "https://refactoringenglish.com", .xml_url = "https://refactoringenglish.com/index.xml" },
    .{ .title = "worksonmymachine.substack.com", .domain = "worksonmymachine.substack.com", .html_url = "https://worksonmymachine.substack.com", .xml_url = "https://worksonmymachine.substack.com/feed" },
    .{ .title = "philiplaine.com", .domain = "philiplaine.com", .html_url = "https://philiplaine.com", .xml_url = "https://philiplaine.com/index.xml" },
    .{ .title = "steveblank.com", .domain = "steveblank.com", .html_url = "https://steveblank.com", .xml_url = "https://steveblank.com/feed/" },
    .{ .title = "bernsteinbear.com", .domain = "bernsteinbear.com", .html_url = "https://bernsteinbear.com", .xml_url = "https://bernsteinbear.com/feed.xml" },
    .{ .title = "danieldelaney.net", .domain = "danieldelaney.net", .html_url = "https://danieldelaney.net", .xml_url = "https://danieldelaney.net/feed" },
    .{ .title = "troyhunt.com", .domain = "troyhunt.com", .html_url = "https://troyhunt.com", .xml_url = "https://www.troyhunt.com/rss/" },
    .{ .title = "herman.bearblog.dev", .domain = "herman.bearblog.dev", .html_url = "https://herman.bearblog.dev", .xml_url = "https://herman.bearblog.dev/feed/" },
    .{ .title = "tomrenner.com", .domain = "tomrenner.com", .html_url = "https://tomrenner.com", .xml_url = "https://tomrenner.com/index.xml" },
    .{ .title = "blog.pixelmelt.dev", .domain = "blog.pixelmelt.dev", .html_url = "https://blog.pixelmelt.dev", .xml_url = "https://blog.pixelmelt.dev/rss/" },
    .{ .title = "martinalderson.com", .domain = "martinalderson.com", .html_url = "https://martinalderson.com", .xml_url = "https://martinalderson.com/feed.xml" },
    .{ .title = "danielchasehooper.com", .domain = "danielchasehooper.com", .html_url = "https://danielchasehooper.com", .xml_url = "https://danielchasehooper.com/feed.xml" },
    .{ .title = "chiark.greenend.org.uk/~sgtatham", .domain = "chiark.greenend.org.uk/~sgtatham", .html_url = "https://chiark.greenend.org.uk/~sgtatham", .xml_url = "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml" },
    .{ .title = "grantslatton.com", .domain = "grantslatton.com", .html_url = "https://grantslatton.com", .xml_url = "https://grantslatton.com/rss.xml" },
    .{ .title = "experimental-history.com", .domain = "experimental-history.com", .html_url = "https://experimental-history.com", .xml_url = "https://www.experimental-history.com/feed" },
    .{ .title = "anildash.com", .domain = "anildash.com", .html_url = "https://anildash.com", .xml_url = "https://anildash.com/feed.xml" },
    .{ .title = "aresluna.org", .domain = "aresluna.org", .html_url = "https://aresluna.org", .xml_url = "https://aresluna.org/main.rss" },
    .{ .title = "michael.stapelberg.ch", .domain = "michael.stapelberg.ch", .html_url = "https://michael.stapelberg.ch", .xml_url = "https://michael.stapelberg.ch/feed.xml" },
    .{ .title = "miguelgrinberg.com", .domain = "miguelgrinberg.com", .html_url = "https://miguelgrinberg.com", .xml_url = "https://blog.miguelgrinberg.com/feed" },
    .{ .title = "keygen.sh", .domain = "keygen.sh", .html_url = "https://keygen.sh", .xml_url = "https://keygen.sh/blog/feed.xml" },
    .{ .title = "mjg59.dreamwidth.org", .domain = "mjg59.dreamwidth.org", .html_url = "https://mjg59.dreamwidth.org", .xml_url = "https://mjg59.dreamwidth.org/data/rss" },
    .{ .title = "computer.rip", .domain = "computer.rip", .html_url = "https://computer.rip", .xml_url = "https://computer.rip/rss.xml" },
    .{ .title = "tedunangst.com", .domain = "tedunangst.com", .html_url = "https://tedunangst.com", .xml_url = "https://www.tedunangst.com/flak/rss" },
};
